#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
# Copyright (c) 2022 Stephan Linz <linz@li-pro.net>

"""
Simple LED blink at Little Wire pin 1.
"""

import time
from sys import stderr, stdout

from verylittlewire import device as vlwd


def setLEDAndWait(lw: vlwd.Device, out: int, state: int, ms: int = 500) -> None:
    lw.digitalWrite(out, state)
    if ms:
        time.sleep(ms / 1000)


try:

    # attach to the Little Wire
    lw = vlwd.Device()

    print("----------------------------------------------------------", file=stdout)
    print(
        "> Little Wire device found with serialNumber: " + lw.readSerialNumber(),
        file=stdout,
    )
    print("----------------------------------------------------------", file=stdout)
    print("> Little Wire firmware version: " + lw.readFirmwareVersion(), file=stdout)

    print("----------------------------------------------------------", file=stdout)
    print("Setup each known pin as input for safty operations.", file=stdout)
    for pin in [vlwd.PIN1, vlwd.PIN2, vlwd.PIN3, vlwd.PIN4]:
        lw.pinMode(pin, vlwd.INPUT)

    print("Press ctrl-c to exit.", file=stdout)
    lw.pinMode(vlwd.PIN1, vlwd.OUTPUT)

    while 1:
        try:
            setLEDAndWait(lw, vlwd.PIN1, vlwd.HIGH)
            setLEDAndWait(lw, vlwd.PIN1, vlwd.LOW)

        except KeyboardInterrupt:
            setLEDAndWait(lw, vlwd.PIN1, vlwd.LOW, 0)
            break

except ValueError as ex:
    print(str(ex), file=stderr)


# vim: tw=80 ts=4 sw=4 sts=4 sta et ai nu
