#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
# Copyright (c) 2022 Stephan Linz <linz@li-pro.net>

"""
Simple button press at Little Wire pin 4 with LED feedback on pin 1.
"""

import time
from sys import stderr, stdout

from verylittlewire import device as vlwd


def getButtonAndDebounce(lw: vlwd.Device, inp: int, state: int, ms: int = 50) -> bool:
    if lw.digitalRead(inp) == state:
        time.sleep(ms / 1000)

        if lw.digitalRead(inp) == state:
            return True

    return False


try:

    # attach to the Little Wire
    lw = vlwd.Device()

    print("----------------------------------------------------------", file=stdout)
    print(
        "> Little Wire device found with serialNumber: " + lw.readSerialNumber(),
        file=stdout,
    )
    print("----------------------------------------------------------", file=stdout)
    print("> Little Wire firmware version: " + lw.readFirmwareVersion(), file=stdout)

    print("----------------------------------------------------------", file=stdout)
    print("Setup each known pin as input for safty operations.", file=stdout)
    for pin in [vlwd.PIN1, vlwd.PIN2, vlwd.PIN3, vlwd.PIN4]:
        lw.pinMode(pin, vlwd.INPUT)
        lw.internalPullup(pin, vlwd.DISABLE)

    print("Press ctrl-c to exit.", file=stdout)
    lw.pinMode(vlwd.PIN1, vlwd.OUTPUT)  # feedback is output
    lw.digitalWrite(vlwd.PIN1, vlwd.LOW)  # feedback LED off
    lw.pinMode(vlwd.PIN4, vlwd.INPUT)  # button is input
    lw.internalPullup(vlwd.PIN4, vlwd.ENABLE)  # button preset with pull-up resistor

    buttonPressed = False
    while 1:
        try:
            button = getButtonAndDebounce(lw, vlwd.PIN4, vlwd.LOW)
            if buttonPressed != button:
                buttonPressed = button

                if button:
                    lw.digitalWrite(vlwd.PIN1, vlwd.HIGH)  # feedback LED on
                    print("Button pressed.")

                else:
                    lw.digitalWrite(vlwd.PIN1, vlwd.LOW)  # feedback LED off
                    print("Button released.")

        except KeyboardInterrupt:
            break

except ValueError as ex:
    print(str(ex), file=stderr)


# vim: tw=80 ts=4 sw=4 sts=4 sta et ai nu
